# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 390)
        self.tableEdit = QtWidgets.QTableWidget(Form)
        self.tableEdit.setGeometry(QtCore.QRect(0, 40, 1081, 71))
        self.tableEdit.setObjectName("tableEdit")
        self.tableEdit.setColumnCount(0)
        self.tableEdit.setRowCount(0)
        self.saveBtn = QtWidgets.QPushButton(Form)
        self.saveBtn.setGeometry(QtCore.QRect(500, 120, 75, 23))
        self.saveBtn.setObjectName("saveBtn")
        self.tableAdd = QtWidgets.QTableWidget(Form)
        self.tableAdd.setGeometry(QtCore.QRect(0, 220, 1081, 71))
        self.tableAdd.setObjectName("tableAdd")
        self.tableAdd.setColumnCount(0)
        self.tableAdd.setRowCount(0)
        self.addBtn = QtWidgets.QPushButton(Form)
        self.addBtn.setGeometry(QtCore.QRect(500, 300, 75, 23))
        self.addBtn.setObjectName("addBtn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(460, 10, 161, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(450, 190, 181, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактирование данных"))
        self.saveBtn.setText(_translate("Form", "Сохранить"))
        self.addBtn.setText(_translate("Form", "Добавить"))
        self.label.setText(_translate("Form", "Секция редактирования записи"))
        self.label_2.setText(_translate("Form", "Секция добавления новой записи"))
